version: 2.1

executors:
  default:
    docker:
      - image: cimg/base:stable

jobs:
  hello:
    executor: default
    resource_class: small
    steps:
      - run:
          name: Hello
          command: echo hello

workflows:
  test:
    jobs:
      - hello
