version: 2.1

setup: true

orbs:
  dynamic: bjd2385/dynamic-continuation@dev:alpha

workflows:
  version: 2

  default:
    jobs:
      - dynamic/continue:
          context: orb-publishing
          modules: |
            /
            /scripts
