version: 2.1

setup: true

orbs:
  dynamic: bjd2385/dynamic-continuation@dev:alpha

workflows:
  test-dynamic-continuation-orb:
    jobs:
      - dynamic/continue:
          debug: true
          context: orb-publishing
          modules: |
            .
            scripts
